# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `minitest-focus` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class Minitest::Test < ::Minitest::Runnable
  include ::Minitest::Assertions
  include ::Minitest::Reportable
  include ::Minitest::Test::LifecycleHooks
  include ::Minitest::Guard
  extend ::Minitest::Guard

  def capture_exceptions; end
  def class_name; end
  def run; end
  def with_info_handler(&block); end

  class << self
    def add_to_filter(name); end
    def filtered_names; end
    def focus(name = T.unsafe(nil)); end
    def i_suck_and_my_tests_are_order_dependent!; end
    def io_lock; end
    def io_lock=(_arg0); end
    def make_my_diffs_pretty!; end
    def parallelize_me!; end
    def runnable_methods; end
    def set_focus_trap; end
    def test_order; end
  end
end

class Minitest::Test::Focus; end
Minitest::Test::Focus::VERSION = T.let(T.unsafe(nil), String)
Minitest::Test::PASSTHROUGH_EXCEPTIONS = T.let(T.unsafe(nil), Array)
Minitest::Test::TEARDOWN_METHODS = T.let(T.unsafe(nil), Array)
