# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `AccountSyncJob`.
# Please instead update this file by running `bin/tapioca dsl AccountSyncJob`.

# typed: strict
class AccountSyncJob
  sig { params(account: T.untyped).returns(T.any(AccountSyncJob, FalseClass)) }
  def self.perform_later(account); end

  sig { params(account: T.untyped).returns(T.untyped) }
  def self.perform_now(account); end
end