# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `GeneratedUrlHelpers`.
# Please instead update this file by running `bin/tapioca dsl GeneratedUrlHelpers`.

# typed: strict
module GeneratedUrlHelpers
  include GeneratedPathHelpersModule
  include GeneratedUrlHelpersModule
  extend GeneratedPathHelpersModule
  extend GeneratedUrlHelpersModule
end