# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `InstitutionSyncJob`.
# Please instead update this file by running `bin/tapioca dsl InstitutionSyncJob`.

# typed: strict
class InstitutionSyncJob
  sig { params(institution: T.untyped).returns(T.any(InstitutionSyncJob, FalseClass)) }
  def self.perform_later(institution); end

  sig { params(institution: T.untyped).returns(T.untyped) }
  def self.perform_now(institution); end
end